apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: kubechart
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres-admin-password
  POSTGRES_DB: kubechart
  PGUSER: deployer_user
  PGPASSWORD: deployer_password
